Add ecommerce layouts
Voog/design-bern pull request #119
Opened 2021-09-07 09:25 UTC by robertpih

Closes #118

2021-09-08 19:26 UTC, tanelj requested changes

2021-09-08 19:26 UTC, tanelj commented on components/html-head.tpl
> +{%- capture breadcrumbsScript -%}
Siin on nüüd see valesti saanud, et `breadcrumbsScript` püütakse küll muutujasse, kuid kasutatakse ainult toote lehel, samas peab selle JS snipet koodi ka siin peale capture'it välja renderdama.

```
{% breadcrumbsScript %}
```

2021-09-09 13:34 UTC, pxska requested changes
* Tootelehel muutuvad stiilid (font vahetub nt):
Enne:
![Screenshot 2021-09-09 at 16 20 04](https://user-images.githubusercontent.com/48313701/132693362-e020a3c2-497c-48d3-920f-f4041e7d843e.png)

Pärast:
![Screenshot 2021-09-09 at 16 20 25](https://user-images.githubusercontent.com/48313701/132693416-7384b93d-1f8c-423c-b469-64b535fe6787.png)

* Tootelistis on hoverimisel "Vaata lähemalt" ära cutitud, kui tootelehel on ostunupp (ehk tootelistis näidatakse hinda):
![Screenshot 2021-09-09 at 16 21 41](https://user-images.githubusercontent.com/48313701/132693607-41b97e02-8fcb-4a42-9e49-8d26b90f3f3d.png)

* Kui product listil ei ole ühtegi nähtavat mitte-product alamlehte, siis see joon võiks kadunud olla:
![Screenshot 2021-09-09 at 16 24 56](https://user-images.githubusercontent.com/48313701/132694089-478db2e6-b97e-478d-b13f-09afef006940.png)

* Paris mallis renderdati product listis nähtav alamleht (mis ei ole product list ega product) ikkagi koos pildiga välja, Bernis mitte – kas siin on mingi piirang või ongi lihtsalt erinevalt saanud ja oli teadlik otsus?

2021-09-09 13:34 UTC, pxska commented on components/content-item.tpl
> +    {% include 'image-src-variable', _data: _imageData, _targetWidth: _targetWidth %}
Siin ka `'` vs `"` jutt.

2021-09-09 13:34 UTC, pxska commented on components/menu-level-2.tpl
> +                <li class="menu-item"><a class="menu-link{% if subitem.selected? %} active{% endif %}{% unless subitem.translated? %} untranslated fci-editor-menuadd{% endunless %}" href="{{ subitem.
Siin samuti `menulink` võimalus?

2021-09-09 13:34 UTC, pxska commented on components/menu-breadcrumbs.tpl
> +            {{ listItem.item.name }}
Siin jääb ka whitespace vahele.

2021-09-09 13:34 UTC, pxska commented on components/product-item.tpl
> +        _entityData.data.image_alt_attr,
Need võiks selguse mõttes samal real olla.

2021-09-20 11:46 UTC, pxska approved these changes
☑️

2021-09-20 13:54 UTC, tanelj requested changes
Toimib kenasti ja õigesti. Leidsin vaid ühe väikese iluvea (lisaks listi indekseerimisele).

* [ ] Toote breadcrumbi stiil ei tunud õige. Peaks sinise asemel ilmselt halli skaalas olema
![Screenshot 2021-09-20 at 16 49 55](https://user-images.githubusercontent.com/378755/134014411-92af685f-fff1-4b54-8473-4d42f740ac47.png)
:

2021-09-20 13:54 UTC, tanelj commented on layouts/product_list.tpl
> +        <section class="content-body content-formatted" {{ edy_intro_edit_text }}>{% content %}</section>
Siin peaks ainult see ala olema `data-search-indexing-allowed=true`

2021-09-21 08:02 UTC, tanelj requested changes
Kaks bugi jäid eile mingil põhjusel kaasa panemata :) 
* [ ] Out of stock label on liiga suu
<img width="451" alt="Screenshot 2021-09-21 at 10 54 22" src="https://user-images.githubusercontent.com/378755/134133811-395f3a8c-2dd4-419f-b636-7d184c0f1f86.png">
* [ ] Tootelisti vaade, kui listi pildile on ALT tekst pandud, siis (FF) kuvatakse seda peale lehe laadimist ja uuesti vaatamist labeliga üksteise peal.
<img width="326" alt="Screenshot 2021-09-21 at 10 56 32" src="https://user-images.githubusercontent.com/378755/134134418-dc2df0cd-9464-40df-93f2-77dbdd2f0b66.png">

2021-09-21 20:16 UTC, tanelj approved these changes

2021-09-22 07:05 UTC, merged