Add auto-generated product layout
Voog/design-bern pull request #121
Opened 2022-02-09 08:33 UTC by pxska

* Add auto-generated product layout
* Add browser hack for Chrome to render crispier images

Closes #120.

2022-02-09 12:11 UTC, PeeterPaal requested changes
Nice! Some comments:

- [ ] Maybe consider adding some margin for the title, price and description.
<img width="455" alt="Screenshot 2022-02-09 at 14 09 16" src="https://user-images.githubusercontent.com/44435196/153198443-5bf7f580-ca33-4946-98be-0892b5e7a99f.png">

2022-02-09 12:11 UTC, PeeterPaal commented on layouts/auto_generated_product.tpl
> +                  <span class="product-price-divider">–</span>
Perhaps let's add some left and right margin for `product-price-divider`

2022-02-10 09:16 UTC, tanelj requested changes
There has some double code.

Also:
* [ ] Out of stock buy button wraps to two lines in Safari (v15.2) preview mode.
<img width="229" alt="Screenshot 2022-02-10 at 10 59 23" src="https://user-images.githubusercontent.com/378755/153375575-b55d094e-1d82-40b3-a83d-5c5ce1d8bc61.png">

2022-02-10 09:16 UTC, tanelj commented on layouts/auto_generated_product.tpl
> +<html class="{% if editmode %}editmode{% else %}public{% endif %}" lang="{{ page.language_code }}" data-view-state="{{ view_mode }}">
There was all ready class `editmode` for `html` tag and there is no need to duplicate it to `data-view-state`.

2022-02-10 09:16 UTC, tanelj commented on sources/javascripts/concat/global/main.js
> +
NB! Now there has two `handleProductPageContent` functions! Please unify!

2022-02-10 09:16 UTC, tanelj commented on sources/javascripts/concat/global/main.js
> +
`handleProductPageContent` is all ready part of `window.site`.

2022-02-10 09:16 UTC, tanelj commented on layouts/auto_generated_product.tpl
> +    template && template.handleProductPageContent();
`handleProductPageContent` is all ready `window.site’ scope.

2022-02-10 09:16 UTC, tanelj commented on sources/stylesheets/components/_image-drop-area.scss
> +  [data-view-state="editmode"] & {
We have all ready `html.editmode` class.

2022-02-10 09:16 UTC, tanelj commented on components/template-variables.tpl
> +{% capture dont_render %}
We have allready `html.editmode` class.

2022-02-10 12:45 UTC, tanelj approved these changes
Nice work!

2022-02-10 14:21 UTC, PeeterPaal requested changes
- [ ] Product gallery is currently not moved under the buy button in mobile view.

2022-02-10 14:36 UTC, PeeterPaal approved these changes
Nice!

2022-02-10 20:55 UTC, merged